[[pages]]
name = "Aircraft"
icon = "âœˆï¸"

[[pages]]
name = "Aircrat_Carriers"
icon = "ğŸš"

[[pages]]
name = "Ammunitions"
icon = "ğŸ›«"

[[pages]]
name = "Amphibious_Assault"
icon = "ğŸ“¡"

[[pages]]
name = "Anti_Tank_Rifles"
icon = "âœˆï¸"

[[pages]]
name = "Armed_Personal_Carriers"
icon = "âœˆï¸"

[[pages]]
name = "Artillery"
icon = "âœˆï¸"

[[pages]]
name = "Assault_Rifles"
icon = "ğŸš"

[[pages]]
name = "Automic_Rifles"
icon = "ğŸ¯"

[[pages]]
name = "Aviation_Subsystems"
icon = "ğŸ’£"

[[pages]]
name = "Battleships"
icon = "ğŸš€"

[[pages]]
name = "Bolt_Action_Rifles"
icon = "ğŸ”«"

[[pages]]
name = "Bomber_Aircraft"
icon = "ğŸ”«"

[[pages]]
name = "Carbines"
icon = "ğŸš€"

[[pages]]
name = "Carrier_Aircraft"
icon = "ğŸš€"

[[pages]]
name = "Civilian_Rifles"
icon = "ğŸ’£"

[[pages]]
name = "Destroyers"
icon = "ğŸŒŠ"

[[pages]]
name = "Drones"
icon = "ğŸ’£"

[[pages]]
name = "Fighter_Aircraft"
icon = "ğŸš€"

[[pages]]
name = "Firearms"
icon = "ğŸš›"

[[pages]]
name = "Frigates"
icon = "ğŸš›"

[[pages]]
name = "Grenade_Launchers"
icon = "ğŸ¯"

[[pages]]
name = "Hand_Grenades"
icon = "ğŸšœ"

[[pages]]
name = "Infantory_Fighting_Vehicles"
icon = "ğŸš€"

[[pages]]
name = "Infantory_Weapons"
icon = "ğŸ’£"

[[pages]]
name = "Larger_Caliber_Rifles"
icon = "ğŸ’£"

[[pages]]
name = "Main_Battle_Tank_(MBT)"
icon = "ğŸ›«"

[[pages]]
name = "Mine_Warfare"
icon = "ğŸ”«"

[[pages]]
name = "Multiple_Launched_Rocket_System"
icon = "ğŸ”«"

[[pages]]
name = "Patrol_Craft"
icon = "ğŸ”«"

[[pages]]
name = "Pistol"
icon = "ğŸ”«"

[[pages]]
name = "Revolver"
icon = "ğŸ”«"

[[pages]]
name = "Self_Loading_Rifles"
icon = "ğŸ”«"

[[pages]]
name = "Shotguns"
icon = "ğŸ’£"

[[pages]]
name = "Special_Arms"
icon = "ğŸ’£"

[[pages]]
name = "Special_Forces_Vehicles"
icon = "ğŸ”«"

[[pages]]
name = "Standart_Caliber_Rifles"
icon = "ğŸ¯"

[[pages]]
name = "Submarines"
icon = "ğŸ”«"

[[pages]]
name = "Vehicle_Subsystems"
icon = "ğŸš€"

[[pages]]
name = "Vehicles"
icon = "ğŸ”«"


